fix AlpesCraft composition id
Change AlpesCraft composition id from 'Alpescraft' to 'AlpesCraft'.

This case issue causes an error when copy pastes the pnpm command from the website:
```
An error occurred:
Error: Cannot find composition with ID "AlpesCraft". Available composition: Sponsor, SponsorWithoutLogo.....
```